"""
Django settings for gst_dashboard project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7!vt#&t0m+#hhx*lo_@@(a5bp27^*$hum$jb$y#rw(_gm@0p&8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://crm.grahaksahaayatakendra.com',
    'https://www.crm.grahaksahaayatakendra.com',
    'http://crm.grahaksahaayatakendra.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dashboard.middleware.DomainAccessMiddleware',  # Add domain access middleware
    'dashboard.middleware.AdminOnlyMiddleware',
]


ROOT_URLCONF = 'gst_dashboard.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dashboard/templates'],  # Include your templates folder here
        'APP_DIRS': True,  # Enable app-level template discovery
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'gst_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'gst_dashboard',
#         'USER': 'admin',
#         'PASSWORD': 'Arjun@moto26',
#         'HOST': '72.167.40.82',
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Set your timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "dashboard/static"),  # Correctly point to the static directory
    
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/redirect/'  # Map this to the role-based redirect view

LOGIN_URL = '/'  # Redirect unauthorized users to the login page

LOGOUT_REDIRECT_URL = 'https://www.grahaksahaayatakendra.com.com/'  # Replace with your desired URL





AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]



AUTH_USER_MODEL = 'dashboard.CustomUser'  # Replace 'dashboard' with your app name

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'info@grahaksahaayatakendra.com'
EMAIL_HOST_PASSWORD = 'SAHAAYATA@123'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'info@grahaksahaayatakendra.com'

# Domain configuration for multi-domain setup
# Domain for Admin, Distributor, and Retailer (v1)
CRM_DOMAIN = 'crm.grahaksahaayatakendra.com'

# Domain for Retailer 2.0 only
CSC_DOMAIN = 'clasclass.com'

# Allowed domains for each platform
CRM_ALLOWED_DOMAINS = [
    'crm.grahaksahaayatakendra.com',        # Main CRM domain
    'www.crm.grahaksahaayatakendra.com',    # With www
    'localhost',                             # For development
    '127.0.0.1',                            # For development
    '127.0.0.1:8000',                       # For development with port
    'localhost:8000',                        # For development with port
]

CSC_ALLOWED_DOMAINS = [
    'clasclass.com',                         # Main CSC domain
    'www.clasclass.com',                     # With www
    'localhost',                             # For development
    '127.0.0.1',                            # For development
    '127.0.0.1:8000',                       # For development with port
    'localhost:8000',                        # For development with port
]

# Legacy domains (for backward compatibility)
RETAILER_2_ALLOWED_DOMAINS = CSC_ALLOWED_DOMAINS
REGULAR_LOGIN_DOMAINS = CRM_ALLOWED_DOMAINS

# CSRF Trusted Origins - Required for CSRF protection

