# Generated by Django 4.1.13 on 2024-12-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch_id',
            field=models.CharField(default='DefaultBranchID', max_length=20, unique=True),
        ),
    ]
