# Generated by Django 4.1.13 on 2024-12-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customuser_pin_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
