# Generated by Django 4.1.13 on 2024-12-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_customuser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Security PIN'),
        ),
    ]
