# Generated by Django 4.1.13 on 2024-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_customer_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
