# Generated by Django 4.1.13 on 2024-12-25 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_customer_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(editable=False, max_length=255, unique=True)),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50)),
                ('id_proof', models.FileField(upload_to='proofs/')),
                ('address_proof', models.FileField(upload_to='proofs/')),
                ('pan_card', models.CharField(blank=True, max_length=255, null=True)),
                ('banking', models.FileField(blank=True, null=True, upload_to='banking/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('others', models.FileField(blank=True, null=True, upload_to='others/')),
                ('service_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Pending', max_length=20)),
                ('service_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
    ]
