# Generated by Django 4.1.13 on 2024-12-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_billingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='ref_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
