# Generated by Django 4.1.13 on 2024-12-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_customuser_wallet_balance_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_retailer',
            field=models.BooleanField(default=False),
        ),
    ]
