# Generated by Django 4.1.13 on 2024-12-27 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_timestamp_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
