# Generated by Django 4.1.13 on 2024-12-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_billingdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
