# Generated by Django 4.1.13 on 2024-12-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_service_service_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
