# Generated by Django 5.1.4 on 2024-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_transaction_options_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required_documents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
