# Generated by Django 5.1.4 on 2024-12-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_service_required_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.service'),
        ),
    ]
