# Generated by Django 5.1.4 on 2024-12-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_billingdetails_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
            preserve_default=False,
        ),
    ]
