# Generated by Django 5.1.4 on 2024-12-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_transaction_options_remove_transaction_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service_name',
        ),
    ]
