# Generated by Django 5.1.4 on 2024-12-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_customuser_mobile_number_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_text_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
