# Generated by Django 5.1.4 on 2025-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_retailer',
            field=models.BooleanField(default=True),
        ),
    ]
