# Generated by Django 5.1.4 on 2025-01-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_customuser_is_retailer_rolerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleRequest',
        ),
    ]
