# Generated by Django 5.1.4 on 2025-01-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_bankingportalaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='billing_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='billing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
