# Generated by Django 5.1.4 on 2025-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_service_billing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=255)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
