# Generated by Django 5.1.4 on 2025-01-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_servicebilling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBilling',
        ),
    ]
