# Generated by Django 5.1.4 on 2025-01-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_delete_servicebilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plain_text_password',
        ),
    ]
