# Generated by Django 5.1.4 on 2025-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_remove_customuser_plain_text_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_text_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
