# Generated by Django 5.1.4 on 2025-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='billing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
