# Generated by Django 5.1.4 on 2025-01-10 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingportalaccessrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
