# Generated by Django 5.1.4 on 2025-01-10 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_bankingportalaccessrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingportalaccessrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
