# Generated by Django 5.1.4 on 2025-01-11 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_customer_added_by_alter_customer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
