# Generated by Django 5.1.4 on 2025-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_remove_customer_added_by_alter_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
    ]
