# Generated by Django 5.1.4 on 2025-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_customuser_is_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_gsk_count',
            field=models.IntegerField(default=0),
        ),
    ]
