# Generated by Django 5.1.4 on 2025-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_customer_current_gsk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_gsk_count',
            field=models.IntegerField(default=0),
        ),
    ]
