# Generated by Django 5.1.4 on 2025-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_customuser_current_gsk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='admin_completed_file',
            field=models.FileField(blank=True, help_text='File uploaded by admin after service completion.', null=True, upload_to='billing_files/completed_services/'),
        ),
    ]
