# Generated by Django 5.1.4 on 2025-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_billingdetails_admin_completed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='admin_completed_file',
            field=models.FileField(blank=True, null=True, upload_to='completed_service_files/'),
        ),
    ]
