# Generated by Django 4.2.11 on 2025-04-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_equipment_options_remove_equipment_category_and_more'),
        ('dashboard', '0003_equipmentorder'),
        ('dashboard', '0071_alter_billingdetails_admin_completed_file'),
    ]

    operations = [
    ]
