# Generated by Django 4.2.11 on 2025-04-24 07:16

from django.db import migrations
from decimal import Decimal

def add_equipment_data(apps, schema_editor):
    Equipment = apps.get_model('dashboard', 'Equipment')
    
    equipment_data = [
        {
            'name': 'High-Speed Thermal Printer',
            'description': 'Professional thermal printer with auto-cutter, USB & LAN ports. Perfect for high-volume receipt printing.',
            'price': Decimal('8999.00'),
            'stock': 10
        },
        {
            'name': 'Mantra L1 Fingerprint Scanner',
            'description': 'UIDAI certified fingerprint scanner for Aadhaar authentication. High-quality optical sensor with 500 DPI resolution.',
            'price': Decimal('2999.00'),
            'stock': 15
        },
        {
            'name': 'Morpho Fingerprint Scanner',
            'description': 'Advanced biometric scanner with FBI PIV certification. Superior image quality and fake finger detection.',
            'price': Decimal('6499.00'),
            'stock': 5
        },
        {
            'name': 'Complete Desktop System',
            'description': 'Full desktop setup including CPU, monitor, keyboard, and mouse. Intel Core i3, 8GB RAM, 256GB SSD.',
            'price': Decimal('35999.00'),
            'stock': 8
        },
        {
            'name': '21.5" LED Monitor',
            'description': 'Full HD LED monitor with HDMI and VGA ports. Anti-glare screen with excellent color accuracy.',
            'price': Decimal('8499.00'),
            'stock': 12
        },
        {
            'name': 'Business CPU',
            'description': 'Intel Core i3 processor, 8GB RAM, 256GB SSD, Windows 11 Pro. Perfect for business applications.',
            'price': Decimal('20999.00'),
            'stock': 6
        },
        {
            'name': 'POS Swipe Machine',
            'description': 'Wireless POS terminal with 4G connectivity. Supports all major cards and UPI payments.',
            'price': Decimal('12999.00'),
            'stock': 10
        },
        {
            'name': 'Professional USB Keyboard',
            'description': 'Ergonomic wired keyboard with numeric keypad. Spill-resistant design with quiet keys and palm rest.',
            'price': Decimal('999.00'),
            'stock': 20
        },
        {
            'name': 'Optical USB Mouse',
            'description': 'High-precision optical mouse with 1200 DPI. Comfortable grip with smooth tracking and responsive buttons.',
            'price': Decimal('499.00'),
            'stock': 25
        }
    ]
    
    for data in equipment_data:
        Equipment.objects.create(**data)

def remove_equipment_data(apps, schema_editor):
    Equipment = apps.get_model('dashboard', 'Equipment')
    Equipment.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0073_equipmentorder_base_price_equipmentorder_gst_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(add_equipment_data, remove_equipment_data),
    ]
