# Generated by Django 4.2.11 on 2025-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
