# Generated by Django 4.2.11 on 2025-05-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_customuser_is_demo_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_demo',
        ),
    ]
