# Generated by Django 4.2.11 on 2025-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_remove_customuser_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('retailer', 'Retailer'), ('distributor', 'Distributor'), ('master_distributor', 'Master Distributor'), ('retailer_2', 'Retailer 2.0'), ('distributor_2', 'Distributor 2.0')], default='retailer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.CharField(blank=True, choices=[('retailer', 'Retailer'), ('distributor', 'Distributor'), ('master_distributor', 'Master Distributor'), ('retailer_2', 'Retailer 2.0'), ('distributor_2', 'Distributor 2.0')], max_length=50, null=True),
        ),
    ]
