# Generated by Django 4.2.11 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_cscservice_cscservicerequest_cscservicedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscservice',
            name='service_color',
            field=models.CharField(default='#007bff', help_text='Hex color code for service card', max_length=7),
        ),
        migrations.AddField(
            model_name='cscservice',
            name='service_icon',
            field=models.CharField(default='mdi mdi-cog', help_text='Material Design Icon class (e.g., mdi mdi-account)', max_length=100),
        ),
    ]
