# Generated by Django 4.2.11 on 2025-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_cscservice_service_color_cscservice_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscservice',
            name='service_image',
            field=models.ImageField(blank=True, help_text='Service card image', null=True, upload_to='csc_services/'),
        ),
    ]
