# Generated by Django 4.2.11 on 2025-07-15 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_cscservice_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer2BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=255, unique=True)),
                ('billing_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='address_proofs/')),
                ('pan_card', models.CharField(blank=True, max_length=255, null=True)),
                ('banking', models.FileField(blank=True, null=True, upload_to='banking/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('others', models.FileField(blank=True, null=True, upload_to='others/')),
                ('service_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Pending', max_length=20)),
                ('service_notes', models.TextField(blank=True, null=True)),
                ('admin_completed_file', models.FileField(blank=True, null=True, upload_to='completed_service_files/')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cscservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
