# Generated by Django 4.2.11 on 2025-07-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_billingdetails_amount_retailer2billingdetails_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscservice',
            name='external_link',
            field=models.URLField(blank=True, help_text='External link for the service (optional)', null=True),
        ),
    ]
