# Generated by Django 4.2.11 on 2026-01-13 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_cscservice_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Upload QR code image', null=True, upload_to='qr_codes/')),
                ('upi_id', models.CharField(default='9336323478@okbizaxis', help_text='UPI ID for payments', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code Settings',
                'verbose_name_plural': 'QR Code Settings',
            },
        ),
    ]
