# Generated by Django 4.2.11 on 2026-01-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_qrcodesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_number', models.CharField(default='09AAJCT1207A1ZT', max_length=50)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=50)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_invoice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration Invoice',
                'verbose_name_plural': 'User Registration Invoices',
            },
        ),
    ]
