# Generated by Django 4.2.11 on 2026-01-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_userregistrationinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationinvoice',
            name='company_stamp',
            field=models.ImageField(blank=True, help_text='Company stamp/seal image', null=True, upload_to='company_stamps/'),
        ),
        migrations.AddField(
            model_name='userregistrationinvoice',
            name='signature',
            field=models.ImageField(blank=True, help_text='Authorized signature image', null=True, upload_to='signatures/'),
        ),
    ]
