# Generated by Django 4.2.11 on 2026-01-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_userregistrationinvoice_company_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationinvoice',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Leave blank for personal account payments', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationinvoice',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Leave blank for personal account payments', max_length=50, null=True),
        ),
    ]
