# Generated by Django 4.2.11 on 2026-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_userregistrationinvoice_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_at',
            field=models.DateTimeField(blank=True, help_text='Set on first portal login', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_disclaimer_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When user closed the wallet recharge disclaimer', null=True),
        ),
    ]
