# Generated by Django 4.2.11 on 2026-04-11 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_wallet_disclaimer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('typed_name', models.CharField(max_length=255)),
                ('signature_image', models.ImageField(upload_to='agreements/signatures/')),
                ('pdf_file', models.FileField(upload_to='agreements/pdfs/')),
                ('email_sent_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
    ]
