# Generated by Django 4.2.11 on 2026-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_agreement_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAgreementText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_body', models.TextField(blank=True, help_text='Paste your full agreement here (plain text). Use blank lines between sections. When this field is filled, it replaces the default portal terms everywhere.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal agreement text',
                'verbose_name_plural': 'Portal agreement text',
            },
        ),
    ]
