# Generated by Django 5.2.7 on 2026-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0092_portal_agreement_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalagreementtext",
            name="terms_body",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Optional: replaces the built-in agreement. "
                    "Placeholders: {{DATE}} (account / ID first created), "
                    "{{NAME}}, {{USER_ID}}, {{AMOUNT}}, {{IP_ADDRESS}}, {{DEVICE}}."
                ),
            ),
        ),
    ]