# Generated by Django 4.2.11 on 2026-07-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_portal_agreement_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabelTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('domain', models.CharField(help_text='Host only, e.g. portal.client.com (no https://)', max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='white_label/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='white_label/favicons/')),
                ('primary_color', models.CharField(default='#0d9488', max_length=20)),
                ('secondary_color', models.CharField(default='#0ea5e9', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('white_label_admin', 'White Label Admin'), ('retailer', 'Retailer'), ('distributor', 'Distributor'), ('master_distributor', 'Master Distributor'), ('retailer_2', 'Retailer 2.0'), ('distributor_2', 'Distributor 2.0')], default='retailer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portalagreementtext',
            name='terms_body',
            field=models.TextField(blank=True, help_text='Optional: replaces the built-in agreement. Placeholders: {{DATE}} (account / ID first created), {{NAME}}, {{USER_ID}}, {{AMOUNT}}, {{IP_ADDRESS}}, {{DEVICE}}.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='NULL = platform (existing GSK). Set for white-label subtree users.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='dashboard.whitelabeltenant'),
        ),
    ]
