# Generated by Django 4.2.11 on 2026-07-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_alter_portalagreementtext_terms_body'),
        ('dashboard', '0093_white_label_tenant_and_user_tenant'),
    ]

    operations = [
    ]
